import board as gc

my_board = gc.Board(board_size=3)

my_board.print_board()
'''
space_list = my_board.get_space_list()
for space in space_list:
   print("---for space " + str(space) + " -------------------")
   left = space.get_left_neighbor()
   right = space.get_right_neighbor()
   above = space.get_above_neighbor()
   below = space.get_below_neighbor()
   print("left: " + str(left))
   print("right: " + str(right))
   print("above: " + str(above))
   print("below: " + str(below))
'''
print("*****************testing up and down movement********************")
my_board.print_board()
my_board.thief.move("down")
print("thief down---------")
my_board.print_board()
my_board.thief.move("down")
print("thief down---------")
my_board.print_board()
my_board.thief.move("up")
print("thief up----------")
my_board.print_board()
print("******************testing moving into occupied spot *************")
my_board.print_board()
my_board.policemen[0].move("right")
print("pman 0 right----------")
my_board.print_board()
print("*****************testing moving left and right***************")
my_board.print_board()
my_board.policemen[1].move("right")
print("pman 1 right----------")
my_board.print_board()
my_board.policemen[1].move("left")
print("pman 1 left-----------")
my_board.print_board()
print("*****************testing moving out of bounds*****************")
my_board.print_board()
my_board.thief.move("up")
print("thief up--------------")
my_board.print_board()
my_board.thief.move("left")
print("thief left------------")
my_board.print_board()
my_board.thief.move("right")
print("thief right-----------")
my_board.print_board()
my_board.policemen[0].move("down")
print("pman 0 down----------")
my_board.print_board()
print("******************thief moving around*************************")
my_board.print_board()
my_board.thief.move("down")
print("thief down")
my_board.print_board()
my_board.thief.move("right")
print("thief right")
my_board.print_board()
my_board.thief.move("down")
print("thief down")
my_board.print_board()
my_board.thief.move("left")
print("thief left")
my_board.print_board()
my_board.thief.move("up")
print("thief up")
my_board.print_board()
my_board.thief.move("left")
print("thief left")
my_board.print_board()
my_board.thief.move("right")
print("thief right")
my_board.print_board()
my_board.thief.place(1,1)
print("place thief at 1, 1")
my_board.print_board()

print("============================testing distance getting=======================")
board = Board(board_size=4)
board.print_board()

print("should be 0: " + str(board.get_distance_between_spaces(1, 1, 1, 1)))
print("should be 1: " + str(board.get_distance_between_spaces(1, 1, 1, 2)))
print("should be 2: " + str(board.get_distance_between_spaces(1, 1, 2, 1)))
print("should be 3: " + str(board.get_distance_between_spaces(1, 1, 2, 2)))
print("should be 4: " + str(board.get_distance_between_spaces(1, 1, 3, 3)))
print("should be 5: " + str(board.get_distance_between_spaces(1, 1, 3, 4)))
print("should be 6: " + str(board.get_distance_between_spaces(0, 0, 3, 0)))
print("should be err: " + str(board.get_distance_between_spaces(1, 1, 20, 1)))
print("should be err: " + str(board.get_distance_between_spaces(1, 1, 20, 1, 11)))
print("should be err: " + str(board.get_distance_between_spaces(1, 1, 20, 1, 12)))
print("should be err: " + str(board.get_distance_between_spaces(1, 1, 20, 1, 13)))
print("should be err: " + str(board.get_distance_between_spaces(1, 1, 20, 1, 14)))
print("should be err: " + str(board.get_distance_between_spaces(1, 1, 20, 1, 15)))
print("should be err: " + str(board.get_distance_between_spaces(1, 1, 20, 1, 16)))


