import board as gc

my_board = gc.Board(board_size=3)

my_board.print_board()
'''
space_list = my_board.get_space_list()
for space in space_list:
   print("---for space " + str(space) + " -------------------")
   left = space.get_left_neighbor()
   right = space.get_right_neighbor()
   above = space.get_above_neighbor()
   below = space.get_below_neighbor()
   print("left: " + str(left))
   print("right: " + str(right))
   print("above: " + str(above))
   print("below: " + str(below))
'''
print("*****************testing up and down movement********************")
my_board.print_board()
my_board.thief.move("down")
print("thief down---------")
my_board.print_board()
my_board.thief.move("down")
print("thief down---------")
my_board.print_board()
my_board.thief.move("up")
print("thief up----------")
my_board.print_board()
print("******************testing moving into occupied spot *************")
my_board.print_board()
my_board.policemen[0].move("right")
print("pman 0 right----------")
my_board.print_board()
print("*****************testing moving left and right***************")
my_board.print_board()
my_board.policemen[1].move("right")
print("pman 1 right----------")
my_board.print_board()
my_board.policemen[1].move("left")
print("pman 1 left-----------")
my_board.print_board()
print("*****************testing moving out of bounds*****************")
my_board.print_board()
my_board.thief.move("up")
print("thief up--------------")
my_board.print_board()
my_board.thief.move("left")
print("thief left------------")
my_board.print_board()
my_board.thief.move("right")
print("thief right-----------")
my_board.print_board()
my_board.policemen[0].move("down")
print("pman 0 down----------")
my_board.print_board()
print("******************thief moving around*************************")
my_board.print_board()
my_board.thief.move("down")
print("thief down")
my_board.print_board()
my_board.thief.move("right")
print("thief right")
my_board.print_board()
my_board.thief.move("down")
print("thief down")
my_board.print_board()
my_board.thief.move("left")
print("thief left")
my_board.print_board()
my_board.thief.move("up")
print("thief up")
my_board.print_board()
my_board.thief.move("left")
print("thief left")
my_board.print_board()
my_board.thief.move("right")
print("thief right")
my_board.print_board()
my_board.thief.place(1,1)
print("place thief at 1, 1")
my_board.print_board()
